version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:80" # Map container port 80 to host port 8000 (for local testing)
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Map host port 80 to container port 80 (Nginx listens on 80)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
