version: "3.8"

services:
  app:
    container_name: hng-stage-2-app
    image: victoribironke/hng-stage-2-task:latest
    restart: always
    networks:
      - app-network

  nginx:
    container_name: hng-stage-2-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    name: hng-stage-2-network
