name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image (to Docker Hub)
        run: |
          docker build -t victoribironke/hng-stage-2-task:latest .
          docker login -u victoribironke -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push victoribironke/hng-stage-2-task:latest

      - name: Deploy to VPS via SSH
        uses: webber/ghaction-ssh@v6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull your-dockerhub-username/your-repo-name:latest
            docker-compose down # Stop and remove existing containers
            docker-compose up -d
